added flatlist animation blog post
notJust-dev/notjustdev pull request #66
Opened 2022-12-15 14:11 UTC by Saad-Bashar

2022-12-16 13:03 UTC, Savinvadim1312 requested changes

2022-12-16 13:03 UTC, Savinvadim1312 commented on content/posts/2022-12-14-react-native-flatlist-animations/index.md
> +We will need to remove some of the noises from our code to work on the last item specifically. We will comment out the current `animatedStyle` which animates the list for now. As it will be very hard
Be specific in what file and what code we have to comment out.

2022-12-19 11:33 UTC, Saad-Bashar commented on content/posts/2022-12-14-react-native-flatlist-animations/index.md
> +git clone https://github.com/Saad-Bashar/ios16-lock-screen-dynamic-time
Cool, I was thinking the same.

2023-01-05 06:01 UTC, Savinvadim1312 approved these changes

2023-01-05 06:01 UTC, merged